apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
   name: letsencrypt-prod
spec:
   acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: 'vishwas.mr.92@gmail.com'
      privateKeySecretRef:
         name: letsencrypt-prod
      http01: {}
